#!/usr/bin/env python
import optparse
import sys
from collections import defaultdict
from simalign import simalign
from tqdm import tqdm


optparser = optparse.OptionParser()
optparser.add_option("-d", "--data", dest="train", default="data/hansards", help="Data filename prefix (default=data)")
optparser.add_option("-e", "--english", dest="english", default="e", help="Suffix of English filename (default=e)")
optparser.add_option("-f", "--french", dest="french", default="f", help="Suffix of French filename (default=f)")
optparser.add_option("-t", "--threshold", dest="threshold", default=0.5, type="float", help="Threshold for aligning with Dice's coefficient (default=0.5)")
optparser.add_option("-n", "--num_sentences", dest="num_sents", default=100000000000, type="int", help="Number of sentences to use for training and alignment")
(opts, _) = optparser.parse_args()
f_data = "%s.%s" % (opts.train, opts.french)
e_data = "%s.%s" % (opts.train, opts.english)

sys.stderr.write("Loading Sim Aligner...")

model = simalign.SentenceAligner(model="xlmr")

for (f, e) in tqdm(zip(open(f_data), open(e_data))):
  result = model.get_word_aligns(f, e)
  for (i, j) in result['mwmf']:
    sys.stdout.write("%i-%i " % (i, j))
  sys.stdout.write("\n")













